baseURL = '/'
languageCode = 'zh-CN'
title = '荒原冒险资源库'
theme = "paper"


[params]
  # color style
  color = 'linen'                           # linen, wheat, gray, light

  # header social icons
  twitter = 'whyya'               # twitter.com/YOUR_TWITTER_ID
  rss = true                                # show rss icon

  # home page profile
  avatar = 'https://whyya-1254698311.cos.ap-shanghai.myqcloud.com/%E9%99%84%E4%BB%B6/FhV5-V_IBcJRwoqaPQ2uTPWJiYsKv2.jpg'                 # gravatar email or image url
  name = 'Whyya'
  bio = '人间五十年'


  # misc
  disableHLJS = true                        # disable highlight.js
  disablePostNavigation = true              # disable post navigation
  monoDarkIcon = true                       # show monochrome dark mode icon
  gravatarCdn = 'GRAVATAR_CDN_LINK'         # e.g. 'https://cdn.v2ex.com/gravatar/'
  graphCommentId = "YOUR_GRAPH_COMMENT_ID"  # use graph comment (disqus alternative)
  math = true                               # enable KaTeX math typesetting globally
  comments = false                          # disable comments for a specific page
